<?php

/**
 * @file
 * Implements hooks to store files on IPFS.
 */

use Drupal\file\FileInterface;
use Cloutier\PhpIpfsApi\IPFS;

/**
 * @file
 * Contains ipfs.module.
 */

/**
 * Implements hook_ENTITY_TYPE_insert() for 'file'.
 */
function ipfs_file_insert(FileInterface $entity) {
  $hash = _ipfs_add($entity);

  if (empty($hash)) {
    return;
  }

  $fields = [
    'hash' => $hash,
    'fid' => $entity->id(),
  ];

  $database = \Drupal::database();
  $database->insert('ipfs_mapping')->fields($fields)->execute();
}

/**
 * Implements hook_ENTITY_TYPE_update() for 'file'.
 */
function ipfs_file_update(FileInterface $entity) {
  $hash = _ipfs_add($entity);

  if (empty($hash)) {
    return;
  }

  $fields = [
    'hash' => $hash,
  ];

  $database = \Drupal::database();
  $database->update('ipfs_mapping')
    ->fields($fields)
    ->condition('fid', $entity->id());
}

/**
 * Adjust image element for IPFS loading.
 *
 * @param mixed $variables
 *   Variables for image element.
 */
function ipfs_preprocess_image(&$variables) {
  if (!empty($variables['attributes']['data-ipfs-src']) || !empty($variables['attributes']['data-ipfs-src-base64'])) {
    $variables['attributes']['src'] = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
  }
}

/**
 * Add a file to IPFS.
 *
 * @param \Drupal\file\FileInterface $entity
 *   The file entity of the file, that should be added.
 *
 * @return string
 *   The hash identifying the file on IPFS.
 */
function _ipfs_add(FileInterface $entity) {
  $settings = \Drupal::config('ipfs.settings');

  $ipfs = new IPFS($settings->get('gateway.address'), $settings->get('gateway.port'), $settings->get('gateway.api_port'));
  $mime = $entity->getMimeType();
  $content = 'data:' . $mime . ';base64,' . base64_encode(file_get_contents($entity->getFileUri()));
  $hash = $ipfs->add($content);
  if (empty($hash)) {
    \Drupal::logger('ipfs')->error('Could not add file to Ipfs');
  }
  return $hash;
}
