ipfs.settings:
  type: config_object
  label: 'IPFS settings'
  mapping:
    gateway:
      type: mapping
      label: 'Settings for the IPFS gateway'
      mapping:
        address:
          type: string
          label: 'IP Address of the gateway'
        port:
          type: integer
          label: 'Port of the gateway'
        api_port:
          type: integer
          label: 'API Port of the gateway'
